name: 080-resusable-workflow-caller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-A:
    uses: punch161/github-actions/.github/workflows/080-reusable-workflow-called.yml@master
    with:
      username: Hamza
    secrets:
      token: ${{ secrets.TOKEN }}

  call-workflow-B:
    uses: punch161/github-actions/.github/workflows/080-reusable-workflow-called.yml@master
    with:
      username: Abdullah
    secrets:
      token: ${{ secrets.TOKEN }}
