
name: downlaod_artifact

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
